[package]
name = "ash-rewrite-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
winit = { version = "0.29", features = ["rwh_06"] }

ash-rewrite = {  path = "../ash-rewrite", features = ["linked"]  } # default-features = false, features = ["linked", "debug", "std", "provisional"]

# TODO: how would ash-window differentiate from the rewritten version and the old version? feature flag perhaps?
ash-window = { path = "../ash-window" }